### ISSUE TITLE
"WWF In Your House" crashes on Raspberry Pi 3

### ISSUE THREAD

**Issue by genius8086** [libretro/pcsx_rearmed#212]
"WWF In Your House" crashes after selecting a character on loading match screen. If Dynamic Recompiler is disabled from the core options, the game progresses and the match starts.

**Comment by gameblabla** [comment]
Known ARM dynarec crash issue with the game. Sadly, it looks like it won't be easily fixable. : /
```sh
Thread 1 "pcsx" received signal SIGILL, Illegal instruction.
0x005404e4 in translation_cache ()
#0  0x005404e4 in translation_cache ()
#1  0x00000000 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
A debugging session is active.

	Inferior 1 [process 12929] will be killed.
```
