### ISSUE TITLE
Lightrec crashes with every game, Linux x86_64

### ISSUE THREAD

**Issue by Exalm** [libretro/pcsx_rearmed#404]
## Description

Games run for one frame, then crash.

Backtrace from RetroArch (no debug symbols)

```
#0  0x0000000000000000 in ?? ()
#1  0x00007fffefaed5c7 in lightrec_emulate_block () from /home/exalm/.var/app/org.libretro.RetroArch/config/retroarch/cores/pcsx_rearmed_libretro.so
#2  0x00007fffefaf26e8 in lightrec_recompiler_run_first_pass () from /home/exalm/.var/app/org.libretro.RetroArch/config/retroarch/cores/pcsx_rearmed_libretro.so
#3  0x00007fffefaefcb7 in ?? () from /home/exalm/.var/app/org.libretro.RetroArch/config/retroarch/cores/pcsx_rearmed_libretro.so
#4  0x00007fffefaefdd7 in lightrec_execute () from /home/exalm/.var/app/org.libretro.RetroArch/config/retroarch/cores/pcsx_rearmed_libretro.so
#5  0x00007fffefac4fdd in ?? () from /home/exalm/.var/app/org.libretro.RetroArch/config/retroarch/cores/pcsx_rearmed_libretro.so
#6  0x00007fffefac5375 in ?? () from /home/exalm/.var/app/org.libretro.RetroArch/config/retroarch/cores/pcsx_rearmed_libretro.so
#7  0x00007fffefb4453c in retro_run () from /home/exalm/.var/app/org.libretro.RetroArch/config/retroarch/cores/pcsx_rearmed_libretro.so
#8  0x000055555564b671 in ?? ()
#9  0x0000555555655bb6 in ?? ()
#10 0x00005555556567a8 in ?? ()
#11 0x00007ffff3c95173 in __libc_start_main () from /usr/lib/x86_64-linux-gnu/libc.so.6
#12 0x000055555562b21e in ?? ()
```

And backtrace from GNOME Games

```
#0  0x0000000000000000 in  ()
#1  0x00007ffff599905f in execute (inter=0x7fffffffdf90, func=<optimized out>) at deps/lightrec/interpreter.c:1101
#2  0x00007ffff599905f in lightrec_int_op (inter=0x7fffffffdf90) at deps/lightrec/interpreter.c:1087
#3  0x00007ffff599905f in lightrec_emulate_block_list (op=<optimized out>, block=0x555555b65280) at deps/lightrec/interpreter.c:1101
#4  0x00007ffff599905f in lightrec_emulate_block (block=block@entry=0x555555b65280, pc=176) at deps/lightrec/interpreter.c:1119
#5  0x00007ffff599e288 in lightrec_recompiler_run_first_pass (block=block@entry=0x555555b65280, pc=pc@entry=0x7fffffffe01c) at deps/lightrec/recompiler.c:272
#6  0x00007ffff599b78b in get_next_block_func (state=state@entry=0x55555563ba00, pc=<optimized out>) at deps/lightrec/lightrec.c:409
#7  0x00007ffff599b8ab in lightrec_execute (state=0x55555563ba00, pc=<optimized out>, target_cycle=<optimized out>) at deps/lightrec/lightrec.c:968
#8  0x00007ffff599b8ef in lightrec_execute_one (state=<optimized out>, pc=<optimized out>) at deps/lightrec/lightrec.c:982
#9  0x00007ffff597068d in lightrec_plugin_execute_block () at libpcsxcore/lightrec/plugin.c:505
#10 0x00007ffff5970a2d in lightrec_plugin_execute () at libpcsxcore/lightrec/plugin.c:551
#11 0x00007ffff59f095c in retro_run () at frontend/libretro.c:2513
#12 0x000055555556d5ed in retro_core_iteration (self=0x5555555a8000) at ../retro-runner/retro-core.c:1591
#13 0x000055555556d7e7 in run_main_loop (self=self@entry=0x5555555a8000) at ../retro-runner/retro-core.c:1486
#14 0x00005555555704fe in retro_main_loop_source_dispatch (source=0x555555b645f0, callback=0x55555556d7d0 <run_main_loop>, user_data=0x5555555a8000) at ../retro-runner/retro-main-loop-source.c:39
#15 0x00007ffff7b72c2e in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff7b72fe0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007ffff7b732d3 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#18 0x0000555555563564 in run_main_loop (error=0x7fffffffe310, filename=<optimized out>, connection=0x55555559e070, loop=0x555555587960) at ../retro-runner/retro-runner.c:41
#19 0x0000555555563564 in main (argc=<optimized out>, argv=<optimized out>) at ../retro-runner/retro-runner.c:98
```

Happened with every game I tried so far, e.g. Castlevania: Symphony of the Night.
## Steps to reproduce

Start a game.

## When did the behavior start?

It doesn't happen with ea884d3029c673e06a4084156ceb662598d8945a, started soon after, probably with the introduction of Lightrec.

## Your device/OS/platform/architecture

Linux, x86_64 (Fedora 32)

**Comment by hizzlekizzle** [comment]
Hmm, I'm able to run games with a self-compiled RetroArch but not with the Snap package (using the same lib e68fbed).

**Comment by Exalm** [comment]
Oh, forgot to mention, I ran both apps in Flatpak.

**Comment by hizzlekizzle** [comment]
Hmm, with that in mind, it seems like it could be a matter of the snap/flatpak sandboxing having a problem with lightrec for some reason. Beetle-psx is fine, though, with the lightrec enabled, right?

**Comment by Exalm** [comment]
![Screenshot from 2020-04-26 04-45-05](https://user-images.githubusercontent.com/1510457/80293423-ccb78700-874e-11ea-9d18-c26192b03e85.png)

Beetle-PSX is fine, yes. (after restart too)

**Comment by Exalm** [comment]
Aha. PCSX ReARMed works with firmware with lightrec, but fails without it.

**Comment by Exalm** [comment]
IDK if it's expected to fail in that case, but if it is, it should probably be automatically disabled when firmware is not present.

**Comment by hizzlekizzle** [comment]
Ah, yeah, that is known. And sure enough, my snap installation didn't have the 'system' dir set correctly. Once I got that working it was fine here, too.

Having it automatically disable the lightrec if there's no BIOS is a good idea, though the HLE BIOS is usually bad news anyway.

**Comment by Exalm** [comment]
Bad news or not, we can't ship BIOS out of the box, and I vastly prefer lower compatibility to an immediate crash 😅️

**Comment by negativeExponent** [comment]
turn off dynarec, use hle = crash. just saying. someone has to clean this up properly, might just as well get rid of hle stuff when compiled with lighrec or whatever till its fixed (assuming its in the works...)
