### ISSUE TITLE
Segmentation fault when starting game from command line.

### ISSUE THREAD

**Issue by orbea** [libretro/pcsx_rearmed#63]
OS: `Slackware64-current`
`RetroArch-2016.09.07_882cddf_master-x86_64-1_git`
`pcsx-rearmed-2016.09.07_201e4c4_master-x86_64-1_git`

Starting games from the command line will result in a segfault or otherwise fail unless a full path is used, which game does not seem to matter.

Segfaults:

```
retroarch -L pcsx_rearmed_libretro.so game.cue

Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007ffff1d22e31 in fseek () from /usr/lib64/debug/libc.so.6
```

Crashes:

```
retroarch -L pcsx_rearmed_libretro.so ./game.cue

unsupported/invalid CD image: ./game.cue
```

Works:
- `retroarch -L pcsx_rearmed_libretro.so directory/game.cue`
- Starting game.cue from the RetroArch menu.

Full gdb log: http://pastebin.com/hfpx3d41

**Comment by orbea** [comment]
Updated backtraces.
```
Thread 1 "retroarch" received signal SIGSEGV, Segmentation fault.
0x00007ffff47a21f1 in fseek () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff47a21f1 in fseek () from /lib64/libc.so.6
#1  0x00007fffef4198bd in opensbifile (isoname=0x7fffef4e6000 <IsoFile> "Lunar - Silver Star Story (Japan) (Disc 1).cue") at libpcsxcore/cdriso.c:1072
#2  0x00007fffef41a277 in ISOopen () at libpcsxcore/cdriso.c:1288
#3  0x00007fffef4a044b in _OpenPlugins () at frontend/main.c:854
#4  0x00007fffef4a0b24 in OpenPlugins () at frontend/main.c:931
#5  0x00007fffef49d7e5 in retro_load_game (info=0xb92a70) at frontend/libretro.c:1276
#6  0x0000000000413ae1 in core_load_game (load_info=0x7fffffffd6a0) at core_impl.c:307
#7  0x0000000000430dc0 in content_file_load (info=0xb92a70, content=0xb92840, content_ctx=0x7fffffffd780, error_string=0x7fffffffd778, special=0x0, additional_path_allocs=0xb92aa0)
    at tasks/task_content.c:632
#8  0x00000000004313b5 in content_file_init (content_ctx=0x7fffffffd780, content=0xb92840, error_string=0x7fffffffd778) at tasks/task_content.c:816
#9  0x0000000000433501 in content_init () at tasks/task_content.c:1996
#10 0x000000000041dcbf in event_init_content () at command.c:1294
#11 0x000000000041de37 in command_event_init_core (data=0xa4a028 <current_core_type>) at command.c:1362
#12 0x000000000041f863 in command_event (cmd=CMD_EVENT_CORE_INIT, data=0xa4a028 <current_core_type>) at command.c:2320
#13 0x00000000004161e8 in retroarch_main_init (argc=4, argv=0x7fffffffe178) at retroarch.c:1382
#14 0x0000000000430390 in content_load (info=0x7fffffffe040) at tasks/task_content.c:283
#15 0x00000000004315f1 in task_load_content (content_info=0x7fffffffe040, content_ctx=0x7fffffffdf50, launched_from_menu=true, launched_from_cli=true, error_string=0x7fffffffdf48)
    at tasks/task_content.c:885
#16 0x0000000000432a7a in task_load_content_callback (content_info=0x7fffffffe040, loading_from_menu=true, loading_from_cli=true) at tasks/task_content.c:1563
#17 0x0000000000432c73 in task_push_load_content_from_cli (core_path=0x0, fullpath=0x0, content_info=0x7fffffffe040, type=CORE_TYPE_PLAIN, cb=0x0, user_data=0x0)
    at tasks/task_content.c:1644
#18 0x0000000000412746 in rarch_main (argc=4, argv=0x7fffffffe178, data=0x0) at frontend/frontend.c:139
#19 0x00000000004127c9 in main (argc=4, argv=0x7fffffffe178) at frontend/frontend.c:183
```
Full GDB log - https://pastebin.com/0KcjsVhr
```
$ retroarch -L /usr/lib64/libretro/pcsx_rearmed_libretro.so Lunar\ -\ Silver\ Star\ Story\ \(Japan\)\ \(Disc\ 1\).cue 
Memcard 2: disabled
Starting PCSX-ReARMed 
Running PCSX Version 1.9 (Jan 21 2019).
psxMap: warning: wanted to map @80000000, got 0x7f203fc18000
Mapped (RAM/scrp/ROM/LUTs/TC):
77000000/1f800000/1fc00000/00000000/00000000
found BIOS file: scph5501.bin
RGB565 supported, using it
plugin: plugins/builtin_gpu
plugin: plugins/builtin_spu
plugin: plugins/builtin_pad
plugin: plugins/builtin_pad
Plugins loaded.
Loaded CD Image: Lunar - Silver Star Story (Japan) (Disc 1).cue[+cue]AddressSanitizer:DEADLYSIGNAL
=================================================================
==5780==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f204869f1f1 bp 0x7ffe63d91570 sp 0x7ffe63d91440 T0)
==5780==The signal is caused by a READ memory access.
==5780==Hint: address points to the zero page.
    #0 0x7f204869f1f0 in __GI_fseek (/lib64/libc.so.6+0x871f0)
    #1 0x7f203fe498bc in opensbifile libpcsxcore/cdriso.c:1072
    #2 0x7f203fe4a276 in ISOopen libpcsxcore/cdriso.c:1288
    #3 0x7f203fed044a in _OpenPlugins frontend/main.c:854
    #4 0x7f203fed0b23 in OpenPlugins frontend/main.c:931
    #5 0x7f203fecd7e4 in retro_load_game frontend/libretro.c:1276
    #6 0x41d173 in core_load_game /home/orbea/gittings/forks/RetroArch/core_impl.c:307
    #7 0x44ade0 in content_file_load tasks/task_content.c:632
    #8 0x44be3d in content_file_init tasks/task_content.c:816
    #9 0x4520cb in content_init tasks/task_content.c:1996
    #10 0x430117 in event_init_content /home/orbea/gittings/forks/RetroArch/command.c:1294
    #11 0x4304df in command_event_init_core /home/orbea/gittings/forks/RetroArch/command.c:1362
    #12 0x43387c in command_event /home/orbea/gittings/forks/RetroArch/command.c:2320
    #13 0x421128 in retroarch_main_init /home/orbea/gittings/forks/RetroArch/retroarch.c:1382
    #14 0x4495b9 in content_load tasks/task_content.c:283
    #15 0x44c535 in task_load_content tasks/task_content.c:885
    #16 0x4508c4 in task_load_content_callback tasks/task_content.c:1563
    #17 0x450ccd in task_push_load_content_from_cli tasks/task_content.c:1644
    #18 0x41a61d in rarch_main frontend/frontend.c:139
    #19 0x41a7e1 in main frontend/frontend.c:183
    #20 0x7f204863ac66 in __libc_start_main (/lib64/libc.so.6+0x22c66)
    #21 0x40fd59 in _start (/media/gittings/forks/RetroArch/retroarch+0x40fd59)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libc.so.6+0x871f0) in __GI_fseek
==5780==ABORTING
```
