### ISSUE TITLE
RetroArch Crashes in Chrono Cross (Switching Between Levels of Elements During Match) when "Enhanced Resolution (Slow)" set to ON

### ISSUE THREAD

**Issue by AzlanCoding** [libretro/pcsx_rearmed#798]
### PCSX-ReARMed Version

r23I c396a64

### Your device

Android Box

### Operating System of your device

Android

### CPU architecture

ARM 32bit

### Issue description

When "Enhanced Resolution (Slow)" Is set to ON, RetroArch will crash because of `pcsx_rearmed_libretro_android.so` when I choose which elements (Special Magic Attacks) I want to use in Chrono Cross during a battle. This was not an issue until I updated the core last week (on friday I think). I first installed the PCSX_ReARMed Core in RetroArch on 11 October 2023, everything was working fine at that point in time. I am using RetroArch running on Android 10 with the NEON GPU plugin and an armabi-v7 CPU architecture.

### Step-by-step reproduction and logs

The [Zip file attached](https://drive.google.com/file/d/1dyaOM11jx33FDB_xt14NGmE8f0RvJteH/view?usp=sharing) contains Chrono Cross and the state I was playing. With the `Enhanced Resolution (Slow)` setting on, load the game and the state file, talk to the man right in front of you then select "Of course". The battle will then start, "attack" the enemy enough times until the LVL is 2 or more, select "elements" and switch between element levels multiple times using Left and right D-PAD keys (or using the Joystick). Doing so should crash RetroArch. (The LVL is located above stamina (sta.) and below your HP)
This happens for every other battle in the game. If needed, I can provide another statefile in another section in the gameplay.<br><br><br>
The following is the logs from the `logcat` command at the time when RetroArch Crashed (Ignore `cutils-trace`)
```
11-11 04:13:11.944 16329 16329 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:12.060 16334 16334 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
11-11 04:13:12.061 16334 16334 F DEBUG   : Build fingerprint: 'google/walley/walleye:10/QP1A.191105.004/eng.cmj.20220714.104828:userdebug/test-keys'
11-11 04:13:12.061 16334 16334 F DEBUG   : Revision: '0'
11-11 04:13:12.061 16334 16334 F DEBUG   : ABI: 'arm'
11-11 04:13:12.072 16334 16334 F DEBUG   : Timestamp: 2023-11-11 04:13:12-0500
11-11 04:13:12.072 16334 16334 F DEBUG   : pid: 8608, tid: 8661, name: Thread-2  >>> com.retroarch <<<
11-11 04:13:12.072 16334 16334 F DEBUG   : uid: 10085
11-11 04:13:12.072 16334 16334 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0xc544c302
11-11 04:13:12.072 16334 16334 F DEBUG   :     r0  c4e95604  r1  c544c302  r2  00000010  r3  00000010
11-11 04:13:12.072 16334 16334 F DEBUG   :     r4  c544c302  r5  00000140  r6  000000a6  r7  00000096
11-11 04:13:12.072 16334 16334 F DEBUG   :     r8  c440152c  r9  00000201  r10 00200000  r11 cc7f3ce8
11-11 04:13:12.072 16334 16334 F DEBUG   :     ip  c4e95e04  sp  cc7f3cb8  lr  00000010  pc  c2f98638
11-11 04:13:12.075 16334 16334 F DEBUG   :
11-11 04:13:12.075 16334 16334 F DEBUG   : backtrace:
11-11 04:13:12.075 16334 16334 F DEBUG   :       #00 pc 00114638  /data/data/com.retroarch/cores/pcsx_rearmed_libretro_android.so (BuildId: fee65803cac7f89308f7302d3ca28bbb050b7748)
11-11 04:13:12.281 16318 16318 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:12.629 16318 16318 W app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
11-11 04:13:12.843 16353 16353 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:13.488 16355 16355 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:13.858 16355 16355 W app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
11-11 04:13:14.074 16370 16370 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:14.567  2013  2013 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_13
11-11 04:13:14.679  2182 16375 W ActivityTaskManager:   Force finishing activity com.retroarch/.browser.retroactivity.RetroActivityFuture
11-11 04:13:14.756 16372 16372 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager: Exception thrown during pause
11-11 04:13:14.828  2182 16375 W ActivityTaskManager: android.os.DeadObjectException
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at android.os.BinderProxy.transactNative(Native Method)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at android.os.BinderProxy.transact(BinderProxy.java:510)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2448)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:135)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:69)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.wm.ActivityStack.startPausingLocked(ActivityStack.java:1702)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.wm.ActivityStack.finishActivityLocked(ActivityStack.java:4033)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.wm.ActivityStack.finishActivityLocked(ActivityStack.java:3975)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.wm.ActivityStack.finishTopCrashedActivityLocked(ActivityStack.java:3860)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.wm.RootActivityContainer.finishTopCrashedActivities(RootActivityContainer.java:1148)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities(ActivityTaskManagerService.java:7242)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:739)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:587)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:476)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.am.AppErrors.crashApplication(AppErrors.java:392)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:9327)
11-11 04:13:14.828  2182 16375 W ActivityTaskManager:   at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:84)
11-11 04:13:14.863  2182  2306 W InputDispatcher: channel '2049ca9 com.retroarch/com.retroarch.browser.retroactivity.RetroActivityFuture (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
11-11 04:13:14.863  2182  2306 E InputDispatcher: channel '2049ca9 com.retroarch/com.retroarch.browser.retroactivity.RetroActivityFuture (server)' ~ Channel is unrecoverably broken and will be disposed!
11-11 04:13:14.897  3307  3307 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@3cc8b07
11-11 04:13:14.936  2182  3270 W system_server: Long monitor contention with owner NativeCrashReport (16375) at int com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities(com.android.server.wm.WindowProcessController, java.lang.String)(ActivityTaskManagerService.java:7241) waiters=1 in boolean com.android.server.wm.ActivityTaskManagerService$LocalService.isGetTasksAllowed(java.lang.String, int, int) for 236ms
11-11 04:13:14.939  2182  2217 W system_server: Long monitor contention with owner NativeCrashReport (16375) at int com.android.server.wm.ActivityTaskManagerService$LocalService.finishTopCrashedActivities(com.android.server.wm.WindowProcessController, java.lang.String)(ActivityTaskManagerService.java:7241) waiters=2 in void com.android.server.wm.InputMonitor$1.run() for 237ms
11-11 04:13:14.947  2182  6629 W InputDispatcher: Attempted to unregister already unregistered input channel '2049ca9 com.retroarch/com.retroarch.browser.retroactivity.RetroActivityFuture (server)'
11-11 04:13:14.959  2182  2213 W Looper  : Slow dispatch took 282ms android.fg h=com.android.server.DropBoxManagerService$DropBoxManagerBroadcastHandler c=null m=1
11-11 04:13:15.102  3166  3166 W TvSearchApp: onTrimMemory level=15
11-11 04:13:15.109  2182  2214 W Looper  : Slow dispatch took 156ms android.ui h=com.android.server.am.ActivityManagerService$UiHandler c=null m=1
11-11 04:13:15.111  2182  2213 W Looper  : Slow delivery took 280ms android.fg h=com.android.server.DropBoxManagerService$DropBoxManagerBroadcastHandler c=null m=1
11-11 04:13:15.111  2182  2213 W Looper  : Slow dispatch took 152ms android.fg h=com.android.server.DropBoxManagerService$DropBoxManagerBroadcastHandler c=null m=1
11-11 04:13:15.126  2182  2213 W Looper  : Drained
11-11 04:13:15.131  4020  4020 W TvSearchApp: onTrimMemory level=15
11-11 04:13:15.134  2182  2216 W ActivityManager: setHasOverlayUi called on unknown pid: 8608
11-11 04:13:15.143  2182  2222 W system_server: Long monitor contention with owner Binder:2182_5 (2911) at void com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied()(ActivityManagerService.java:1514) waiters=3 in void com.android.server.am.BroadcastQueue.processNextBroadcast(boolean) for 151ms
11-11 04:13:15.155  1878  1878 E lowmemorykiller: Kill 'com.google.android.gms' (8805), uid 10028, oom_adj 905 to free 89924kB
11-11 04:13:15.164  2182  2222 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
11-11 04:13:15.203 16372 16372 W app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
11-11 04:13:15.165  2182  2222 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
11-11 04:13:15.250  2182  2216 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{40485c9 u0 com.retroarch/.browser.retroactivity.RetroActivityFuture t-1 f}
11-11 04:13:15.431 16400 16400 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:15.999  3307  3307 W Glide   : Load failed for  with size [1280x720]
11-11 04:13:15.999  3307  3307 W Glide   : class com.bumptech.glide.c.b.p: Failed to load resource
11-11 04:13:16.219 16404 16404 W gle.android.gm: JIT profile information will not be recorded: profile file does not exits.
11-11 04:13:16.219 16404 16404 W gle.android.gm: JIT profile information will not be recorded: profile file does not exits.
11-11 04:13:16.262 16426 16426 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:16.672 16426 16426 W app_process: JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
11-11 04:13:16.996 16503 16503 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:17.916 16545 16545 E cutils-trace: Error opening trace file: No such file or directory (2)
11-11 04:13:17.926 16545 16545 W app_process: Could not reserve sentinel fault page
11-11 04:13:18.025  3307 16428 W tvlauncher.fre: resources.arsc in APK '/data/app/com.apkpure.aegon-SOqb7VA3QTC7_m0OKmDIKQ==/base.apk' is compressed.
11-11 04:13:18.121  2182  3112 E TaskPersister: File error accessing recents directory (directory doesn't exist?).
```
The Zip file attached also includes `tombstone_13` which is generated when an application crashes. It provides more details about the crash and can be opened with Notepad or any other text editor.

**Comment by AzlanCoding** [comment]
Thank you so much, it works very well now. I will now delete the zip file.
